config/routes.rb
InviteApp::Application.routes.draw do
  resources :users do
    resources :events
  end

  resources :events do
    resources :invites
  end

  resources :invites 

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :invites

  # def user_name=(name)
  #   self.name = User.find_or_create_by(:name => name)
  # end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :event

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new(:user_id => params[:user_id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :user_id)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def new
    @invites = Invite.where(:event_id => params[:event_id])
    @invite = Invite.new(:event_id => params[:event_id])
  end

  def create
    @invite = Invite.new(:name => params[:invite][:name], :event_id => params[:invite][:event_id])
    @invite.save
    redirect_to new_event_invite_path(@invite.event_id)
  end

  def show
  end

  def edit
    @invite = Invite.find(params[:id])
  end

  def update
    @invite = Invite.find(params[:id])
    @invite.rsvp = true
    @invite.save
    redirect_to event_path(@invite.event)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(@user)
  end



  private

  def user_params
    params.require(:user).permit(:name, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper

  def attendee_list(invite)
    if invite.rsvp
      "Attending"
    else
      link_to 'RSVP', edit_invite_path(invite)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<br>
<br>

<div class="container">

<h1>Editing event</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

</div>

app/views/events/index.html.erb
<br>
<br>

<div class="container">
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Users', users_path %>

</div>

app/views/events/new.html.erb
<br>
<br>

<div class="container">

<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

</div>

app/views/events/show.html.erb
<br>
<br>
<br>

<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Event Creator:</strong>
  <%= @event.user.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Invite People', new_event_invite_path(@event) %>

<br>
<br>

<%= render 'invites/invitees', :invites => @event.invites %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

</div>

app/views/invites/_invitees.html.erb
<h3>Invitees</h3>

<ul>
  <% invites.each do |invite| %>
    <li><%= invite.name %> | 
     <%= attendee_list(invite) %>
   </li>
    <% end %>
</ul>

app/views/invites/edit.html.erb
<br>
<br>
<br>

<div class="container">

<h2>Please RSVP!</h2>

<br>

<%= form_for(@invite) do |f| %>
  <div class="actions">
    <%= f.submit "I'm attending!" %>
  </div>
<% end %>

</div>

app/views/invites/new.html.erb
<br>
<br>
<br>
<br>

<div class="container">

<strong><%= link_to @invite.event.name, event_path(@invite.event) %></strong>

<hr>
<br>

<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>
<hr>

<h3>Invitees</h3>

<ul>
  <% @invites.each do |invite| %>
    <li><%= invite.name %></li>
  <% end %>
</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "invite_app" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "slate", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


<%= yield %>

  <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Invite App</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Events', events_path %></li>
            <li><%= link_to 'Invite', new_event_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <%= javascript_include_tag "slate" %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<br>
<br>

<div class="container">

<h1>Edit User</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<br>
<br>

<div class="container">
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<br>
<br>

<div class="container">
<h1>New User</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', users_path %>

</div>

app/views/users/show.html.erb
<br>
<br>
<br>

<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Events Created:</strong>
  <ul>
  <% @user.events.each do |event| %>
    <li><%= link_to event.name, user_event_path(@user, event) %>
    </li>
  <% end %>
  </ul>
</p>

<br>
<strong><%= link_to 'Create New Event', new_user_event_path(@user) %></strong>
<br>
<br>
<br>
<%= link_to 'Back', users_path %>
</div>